# General

For more informations, see the documentation *LLM and GenAI*.

# Import & Configs

In [48]:
import json
import pandas as pd
from IPython.display import display

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [47]:
%reload_ext autoreload
%autoreload 2

from src.preprocessing.query_processing import clean_query

# Questions Set

In [4]:
with open(
    "../data/evaluations/gold_questions.json"
) as f:

    questions = json.load(f)

questions

[{'question': 'What is glioblastoma?'},
 {'question': 'How is glioblastoma prognosis evaluated?'},
 {'question': 'What MRI techniques are used for glioblastoma?'},
 {'question': 'What is peritumoral edema?'},
 {'question': 'What is pseudoprogression?'},
 {'question': 'How is tumor progression detected?'},
 {'question': 'What biomarkers are associated with glioblastoma?'},
 {'question': 'What are the limitations of MRI in glioma diagnosis?'},
 {'question': 'How is overall survival measured?'},
 {'question': 'What treatments are commonly used for glioblastoma?'}]

# Evaluation Dataframe

In [16]:
df_corpus_eval = pd.DataFrame({
    "Question": [list(q.values())[0] for q in questions],
    "Coverage": None,
    "Difficulty": None,
    "Comments": ""
})

df_corpus_eval

,Question,Coverage,Difficulty,Comments
0,What is glioblastoma?,None,None,
1,How is glioblastoma prognosis evaluated?,None,None,
2,What MRI techniques are used for glioblastoma?,None,None,
3,What is peritumoral edema?,None,None,
4,What is pseudoprogression?,None,None,
5,How is tumor progression detected?,None,None,
6,What biomarkers are associated with glioblastoma?,None,None,
7,What are the limitations of MRI in glioma diag...,None,None,
8,How is overall survival measured?,None,None,
9,What treatments are commonly used for glioblas...,None,None,

# Documents Corpus Upload

In [17]:
def  get_documents_df():
    documents = []
    
    with open("../data/processed/clean_documents.jsonl", "r") as f:
        for line in f:
            documents.append(json.loads(line))

    df = pd.DataFrame(documents)
    return df

In [18]:
df = get_documents_df()
df.head()

,pmid,title,abstract,year,text
0,42200192,Prediction of treatment failure in patients wi...,BACKGROUND: Predicting early treatment failure...,2026,Prediction of treatment failure in patients wi...
1,42200191,Imaging patterns of glioblastoma progression: ...,BACKGROUND: Glioblastoma is the most aggressiv...,2026,Imaging patterns of glioblastoma progression: ...
2,42198443,Antitumor Activity of Cannabinoids and Their I...,Background: Cannabinoids are studied as antica...,2026,Antitumor Activity of Cannabinoids and Their I...
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric...,Pediatric brain tumors are highly prevalent an...,2026,Ultrasound-Enhanced Drug Delivery in Pediatric...
4,42195335,Artificial Intelligence-Based MRI Segmentation...,(1) Background: Differentiating between gliobl...,2026,Artificial Intelligence-Based MRI Segmentation...

# Research In Corpus

In [27]:
def search_corpus(keyword, df, n=10):

    matches = df[
        df["text"]
        .str.contains(
            keyword,
            case=False,
            na=False
        )
    ]

    return matches[
        ["pmid", "title", "year"]
    ].head(n)

In [23]:
pd.set_option('display.max_colwidth', None)

In [28]:
search_corpus(
    "glioblastoma",
    df
)

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
11,42192376,Exploring the value of peritumoral brain zone for classification of two malignant brain tumors based on the MRI interpretable models,2026
13,42189415,Peripheral hematological landscapes as biomarkers for detecting postoperative progression in glioblastoma multiforme: a multivariable risk scoring approach,2026
21,42183985,A data-driven scientific approach to explore the relationship between MGMT methylation and imaging phenotype in glioblastoma,2026

In [29]:
search_corpus(
    "pseudoprogression",
    df
)

,pmid,title,year
16,42185659,Clinical utility of liquid biopsy in distinguishing true progression from radiation necrosis and pseudoprogression in malignant brain tumor,2026
52,42162948,"Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study",2026
79,42147927,Diffusion tensor image analysis along the perivascular space may serve as a potential biomarker for differentiating glioma recurrence from pseudoprogression: a preliminary study,2026
159,42105112,Integrating ConvNeXt tiny and radiomics in a nomogram to differentiate true progression from pseudoprogression in glioma,2026
213,42073593,"Extracellular Vesicle-Associated miRNAs in Glioblastoma: Mechanisms, Biomarkers, Therapies, and Links to Neurodegeneration",2026
245,42046770,Utility of dynamic (18)F-fluoroethyl-L-tyrosine positron emission tomography in determining pseudoprogression from tumor recurrence in the 6 months following radiation therapy for glioblastoma,2026
405,41916447,Chemical exchange saturation transfer (CEST) imaging reveals tumor-specific molecular changes in adult gliomas after radiotherapy,2026

In [30]:
search_corpus(
    "overall survival",
    df
)

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
33,42177147,Habitat-informed MRI Radiomics and Deep Learning Fusion for Short-Term Survival Prediction in Patients with Glioblastoma: Exploratory Radiogenomic and Immune Correlates,2026
38,42173137,PATHY-inspired partial tumor irradiation on a small-animal irradiator: workflow development and first therapeutic evaluation in glioma,2026
45,42169480,Incremental feature fusion based time series forecasting with cumulative risk constraint for longitudinal overall survival prediction,2026
52,42162948,"Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study",2026
59,42158772,Preoperative MR Perfusion and Intraoperative MR Imaging in Predicting Surgical Resectability and Quality of Life Outcomes in High-Grade Glioma Patients: A Prospective Cohort Analysis and Case Study,2026
60,42158701,Concurrent chemoradiotherapy with temozolomide in newly pediatric diffuse intrinsic pontine glioma: clinical outcomes and safety analysis,2026

# Evaluation

In [62]:
def list_to_regex(words):
    regex_str = words.replace(' ', '|')
    return regex_str

In [65]:
for item in questions:
    
    question = item["question"]
    print(f'{question:-^80}')

    keywords = clean_query(question)
    keywords = list_to_regex(keywords)
    
    output = search_corpus(
        keywords,
        df
    )
    
    display(output)
    print("\n\n")

-----------------------------What is glioblastoma?------------------------------
Original query: What is glioblastoma?
Processed query: glioblastoma
glioblastoma

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
11,42192376,Exploring the value of peritumoral brain zone for classification of two malignant brain tumors based on the MRI interpretable models,2026
13,42189415,Peripheral hematological landscapes as biomarkers for detecting postoperative progression in glioblastoma multiforme: a multivariable risk scoring approach,2026
21,42183985,A data-driven scientific approach to explore the relationship between MGMT methylation and imaging phenotype in glioblastoma,2026

--------------------How is glioblastoma prognosis evaluated?--------------------
Original query: How is glioblastoma prognosis evaluated?
Processed query: glioblastoma prognosis evaluated
glioblastoma|prognosis|evaluated

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
9,42192905,Association of Iba1-Positive Macrophages and B7-H3-Positive Tumor Cells with Tumor Growth Kinetics in WHO Grade II Meningioma: A Pilot Watch-and-Wait Cohort Study,2026
11,42192376,Exploring the value of peritumoral brain zone for classification of two malignant brain tumors based on the MRI interpretable models,2026

-----------------What MRI techniques are used for glioblastoma?-----------------
Original query: What MRI techniques are used for glioblastoma?
Processed query: mri techniques used for glioblastoma
mri|techniques|used|for|glioblastoma

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric Neuro-Oncology: A New Therapeutic Strategy,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
9,42192905,Association of Iba1-Positive Macrophages and B7-H3-Positive Tumor Cells with Tumor Growth Kinetics in WHO Grade II Meningioma: A Pilot Watch-and-Wait Cohort Study,2026

---------------------------What is peritumoral edema?---------------------------
Original query: What is peritumoral edema?
Processed query: peritumoral edema
peritumoral|edema

,pmid,title,year
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
11,42192376,Exploring the value of peritumoral brain zone for classification of two malignant brain tumors based on the MRI interpretable models,2026
12,42190843,Integrated Intratumoral and peritumoral APTw and ADC assessment for preoperative glioma grading: A multicenter study,2026
19,42184434,Tumor-mimicking primary CNS vasculitis: illustrative case,2026
23,42182936,Multimodal brain MRI and clinical data in olfactory groove meningioma: a prospective data report,2026
38,42173137,PATHY-inspired partial tumor irradiation on a small-animal irradiator: workflow development and first therapeutic evaluation in glioma,2026
44,42169789,Topological feature-driven TabPFN model for prediction of enlarged hemorrhage and edema after tumor resection in meningiomas,2026

---------------------------What is pseudoprogression?---------------------------
Original query: What is pseudoprogression?
Processed query: pseudoprogression
pseudoprogression

,pmid,title,year
16,42185659,Clinical utility of liquid biopsy in distinguishing true progression from radiation necrosis and pseudoprogression in malignant brain tumor,2026
52,42162948,"Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study",2026
79,42147927,Diffusion tensor image analysis along the perivascular space may serve as a potential biomarker for differentiating glioma recurrence from pseudoprogression: a preliminary study,2026
159,42105112,Integrating ConvNeXt tiny and radiomics in a nomogram to differentiate true progression from pseudoprogression in glioma,2026
213,42073593,"Extracellular Vesicle-Associated miRNAs in Glioblastoma: Mechanisms, Biomarkers, Therapies, and Links to Neurodegeneration",2026
245,42046770,Utility of dynamic (18)F-fluoroethyl-L-tyrosine positron emission tomography in determining pseudoprogression from tumor recurrence in the 6 months following radiation therapy for glioblastoma,2026
405,41916447,Chemical exchange saturation transfer (CEST) imaging reveals tumor-specific molecular changes in adult gliomas after radiotherapy,2026

-----------------------How is tumor progression detected?-----------------------
Original query: How is tumor progression detected?
Processed query: tumor progression detected
tumor|progression|detected

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric Neuro-Oncology: A New Therapeutic Strategy,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
9,42192905,Association of Iba1-Positive Macrophages and B7-H3-Positive Tumor Cells with Tumor Growth Kinetics in WHO Grade II Meningioma: A Pilot Watch-and-Wait Cohort Study,2026

---------------What biomarkers are associated with glioblastoma?----------------
Original query: What biomarkers are associated with glioblastoma?
Processed query: biomarkers associated with glioblastoma
biomarkers|associated|with|glioblastoma

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric Neuro-Oncology: A New Therapeutic Strategy,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
9,42192905,Association of Iba1-Positive Macrophages and B7-H3-Positive Tumor Cells with Tumor Growth Kinetics in WHO Grade II Meningioma: A Pilot Watch-and-Wait Cohort Study,2026

--------------What are the limitations of MRI in glioma diagnosis?--------------
Original query: What are the limitations of MRI in glioma diagnosis?
Processed query: limitations of mri in glioma diagnosis
limitations|of|mri|in|glioma|diagnosis

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric Neuro-Oncology: A New Therapeutic Strategy,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
9,42192905,Association of Iba1-Positive Macrophages and B7-H3-Positive Tumor Cells with Tumor Growth Kinetics in WHO Grade II Meningioma: A Pilot Watch-and-Wait Cohort Study,2026

-----------------------How is overall survival measured?------------------------
Original query: How is overall survival measured?
Processed query: overall survival measured
overall|survival|measured

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
12,42190843,Integrated Intratumoral and peritumoral APTw and ADC assessment for preoperative glioma grading: A multicenter study,2026
13,42189415,Peripheral hematological landscapes as biomarkers for detecting postoperative progression in glioblastoma multiforme: a multivariable risk scoring approach,2026
20,42184015,Comparative benefits of particle embolization versus liquid agents in preoperative management of meningiomas: A Systematic Review and Meta-analysis,2026

--------------What treatments are commonly used for glioblastoma?---------------
Original query: What treatments are commonly used for glioblastoma?
Processed query: treatments commonly used for glioblastoma
treatments|commonly|used|for|glioblastoma

,pmid,title,year
0,42200192,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,2026
1,42200191,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,2026
2,42198443,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2026
3,42198270,Ultrasound-Enhanced Drug Delivery in Pediatric Neuro-Oncology: A New Therapeutic Strategy,2026
4,42195335,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,2026
5,42195211,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",2026
6,42193885,The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,2026
7,42193877,Reprogramming the Immunosuppressive Microenvironment in Glioblastoma Through Oncolytic Herpes Simplex Virus Therapy: A Systematic Review,2026
8,42192946,Prediction of Overall Survival in Glioblastoma Using Early Postoperative Reduction in FLAIR Lesion Volume After Gross Total Resection,2026
10,42192781,Advancing Brain Tumor Diagnosis Using Deep Learning: A Systematic and Critical Review on Methodological Approaches to Glioma Segmentation and Classification Through Multiparametric MRI,2026

| Question  | Coverage | Difficulty | Comments |
|:-----|:-----:|:-----:|:-----|
| Q1 | 2 | 4 | many articles on glioblastoma, but few review or summary papers |
| Q2 | 4 | 3 | topic that is very much present but scattered |
| Q3 | 5 | 5 | MRI is ubiquitous in the corpus |
| Q4 | 3 | 2 | few relevant articles, but little definitional content |
| Q5 |  5 | 5 | the term appears directly in several titles |
| Q6 |  4 | 4 | many articles on progression, imaging, and biomarkers |
| Q7 |  4 | 3 | topic covered but very broad |
| Q8 |  2 | 2 | few articles explicitly focus on limitations |
| Q9 |  2 | 2 | many articles use “OS,” but few explain what it means |
| Q10 |  2 | 2 | few treatments are mentioned, but there is no review of treatment options |

**Corpus coverage:**

| Score | Meaning            |
| ----- | ------------------------ |
| 1     | absent                  |
| 2     | very partial           |
| 3     | present but incomplete |
| 4     | well covered            |
| 5     | fully covered    |

**Retrieval Difficulty:**

| Score | Meaning  |
| ----- | -------------- |
| 1     | very difficult |
| 2     | difficult      |
| 3     | average        |
| 4     | easy         |
| 5     | trivial       |

# Dowload Results

In [79]:
rows = []

for item in questions:

    question = item["question"]

    keywords = clean_query(question)
    regex_query = list_to_regex(keywords)

    output = search_corpus(
        regex_query,
        df
    )

    rows.append({
        "question": question,

        "keywords": keywords,
        "regex_query": regex_query,

        "n_results (max:10)": len(output),

        "pmid_1": output.iloc[0]["pmid"] if len(output) > 0 else None,
        "pmid_2": output.iloc[1]["pmid"] if len(output) > 1 else None,
        "pmid_3": output.iloc[2]["pmid"] if len(output) > 2 else None,

        "title_1": output.iloc[0]["title"] if len(output) > 0 else None,
        "title_2": output.iloc[1]["title"] if len(output) > 1 else None,
        "title_3": output.iloc[2]["title"] if len(output) > 2 else None,
    })

df_corpus_eval = pd.DataFrame(rows)

#df_corpus_eval.head()

Original query: What is glioblastoma?
Processed query: glioblastoma
Original query: How is glioblastoma prognosis evaluated?
Processed query: glioblastoma prognosis evaluated
Original query: What MRI techniques are used for glioblastoma?
Processed query: mri techniques used for glioblastoma
Original query: What is peritumoral edema?
Processed query: peritumoral edema
Original query: What is pseudoprogression?
Processed query: pseudoprogression
Original query: How is tumor progression detected?
Processed query: tumor progression detected
Original query: What biomarkers are associated with glioblastoma?
Processed query: biomarkers associated with glioblastoma
Original query: What are the limitations of MRI in glioma diagnosis?
Processed query: limitations of mri in glioma diagnosis
Original query: How is overall survival measured?
Processed query: overall survival measured
Original query: What treatments are commonly used for glioblastoma?
Processed query: treatments commonly used for glioblastoma

In [80]:
df_corpus_eval["Coverage"] = [2,4,5,3,5,4,4,2,2,2]
df_corpus_eval["Difficulty"] = [4,3,5,2,5,4,3,2,2,2]
df_corpus_eval["Comments"] = [
    "many articles on glioblastoma, but few review or summary papers",
    "topic that is very much present but scattered",
    "MRI is ubiquitous in the corpus",
    "few relevant articles, but little definitional content",
    "the term appears directly in several titles",
    "many articles on progression, imaging, and biomarkers",
    "topic covered but very broad",
    "few articles explicitly focus on limitations",
    "many articles use “OS,” but few explain what it means",
    "few treatments are mentioned, but there is no review of treatment options"
]

In [81]:
df_corpus_eval.head()

,question,keywords,regex_query,n_results (max:10),pmid_1,pmid_2,pmid_3,title_1,title_2,title_3,Coverage,Difficulty,Comments
0,What is glioblastoma?,glioblastoma,glioblastoma,10,42200192,42200191,42198443,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,2,4,"many articles on glioblastoma, but few review or summary papers"
1,How is glioblastoma prognosis evaluated?,glioblastoma prognosis evaluated,glioblastoma|prognosis|evaluated,10,42200192,42200191,42198443,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,4,3,topic that is very much present but scattered
2,What MRI techniques are used for glioblastoma?,mri techniques used for glioblastoma,mri|techniques|used|for|glioblastoma,10,42200192,42200191,42198443,Prediction of treatment failure in patients with glioblastoma with perfusion MRI and molecular biomarkers,Imaging patterns of glioblastoma progression: Comparative analysis of sequential proton boost versus conventional photon therapy,Antitumor Activity of Cannabinoids and Their Interaction with Chemotherapy: A Systematic Review and Meta-Analysis of Preclinical Evidence,5,5,MRI is ubiquitous in the corpus
3,What is peritumoral edema?,peritumoral edema,peritumoral|edema,10,42195335,42195211,42193885,Artificial Intelligence-Based MRI Segmentation in Glioblastoma and Single Brain Metastasis: An Exploratory Study of Diagnostic and Prognostic Value,"Beyond Tumor Volume: An Integrated Radiological Model of Tumor Load, Anatomical Spread, and Mass Effect for Survival Prediction in Adult Grade 4 Diffuse Astrocytic Tumors",The Biomechanics of Glioblastoma: Why Glioblastoma Models and Clinical Reality Diverge,3,2,"few relevant articles, but little definitional content"
4,What is pseudoprogression?,pseudoprogression,pseudoprogression,7,42185659,42162948,42147927,Clinical utility of liquid biopsy in distinguishing true progression from radiation necrosis and pseudoprogression in malignant brain tumor,"Impact on survival of glioblastoma patient's in relation to the imaging of the peri-surgical area: a multi-parametric diffusion MRI, perfusion MRI and [11C]MET PET study",Diffusion tensor image analysis along the perivascular space may serve as a potential biomarker for differentiating glioma recurrence from pseudoprogression: a preliminary study,5,5,the term appears directly in several titles

In [83]:
version = 2
model = "qwen2.5:1.5b"
step = "article_retrieval"

df_corpus_eval.to_csv(
    f"../data/evaluations/V{version}_{step}_evalN9_corpus-{model}.csv",
    index=False
)

___

In [84]:
summary = {
    "coverage": df_corpus_eval["Coverage"].mean(),
    "difficulty": df_corpus_eval["Difficulty"].mean(),
}

In [85]:
print(summary)

{'coverage': np.float64(3.3), 'difficulty': np.float64(3.2)}

Means:

| Coverage  | Difficulty |
|:-----|:-----:|
| 3.3 | 3.2 |

# Meta articles/reviews Proportion

In [51]:
review_mask = df["title"].str.contains(
    "review|systematic review|meta-analysis|guideline",
    case=False,
    na=False
)

#df[review_mask]
len(df[review_mask])

50

In [52]:
100 * len(df[review_mask]) / len(df)

10.460251046025105

Correct ratio.

In [67]:
search = ["review","systematic review","meta-analysis","guideline"]

results = {
    "type": [],
    "count": [],
    "ratio":[]
}

for keyword in search:
    review_mask = df["title"].str.contains(
        keyword,
        case=False,
        na=False
    )

    nb = len(df[review_mask])
    ratio = 100 * nb / len(df)

    results["type"].append(keyword)
    results["count"].append(nb)
    results["ratio"].append(ratio)

results["type"].append("Total")
results["count"].append(len(df))
results["ratio"].append("100")

results = pd.DataFrame(results)
results

                type  count      ratio
0             review     49  10.251046
1  systematic review     19   3.974895
2      meta-analysis     10    2.09205
3          guideline      2    0.41841
4              Total    478        100